// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// Correct Code ✅
// import type { Metadata } from "next";
// import { Sarabun } from "next/font/google";
// import "./globals.css";
// import { AuthProvider } from '@/context/AuthContext'; 
// const sarabun = Sarabun({
//   subsets: ["latin", "thai"],
//   weight: ["400", "700"],
// });

// export const metadata: Metadata = {
//   title: "ระบบจัดเก็บเอกสาร",
//   description: "Document Management System",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="th" data-theme="light">
//       <body className={sarabun.className}>
//          <AuthProvider> 
//         {children}
//         </AuthProvider>
//         </body>
//     </html>
//   );
// }

// src/app/layout.tsx
// This file does NOT need 'use client' if it only sets up providers and metadata.
// Components wrapped by providers can be client components.

import type { Metadata } from 'next';
import { Sarabun } from 'next/font/google'; // Assuming Sarabun is correctly configured
import './globals.css'; // Your global styles
import { AuthContextProvider } from '@/context/AuthContext'; // Import AuthContextProvider
//import ResponsiveSidebar from '@/components/ResponsiveSidebar'; // Import ResponsiveSidebar

const sarabun = Sarabun({
  subsets: ['latin', 'thai'],
  weight: ['400', '700'],
  variable: '--font-sarabun', // Define as a CSS variable for global use
});

// Define metadata for the application (optional but good practice)
export const metadata: Metadata = {
  title: 'ระบบจัดการเอกสาร',
  description: 'ระบบจัดการเอกสารราชการ',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Ensure there is absolutely no whitespace directly between <html> and <body>,
    // or before <html>, or after </html>.
    // The <html lang="th"> tag must be the direct and only child of the RootLayout component's return.
    // Apply Sarabun font globally via CSS variable if needed, or directly via className
    <html lang="th" data-theme="light" className={sarabun.className}>
      <head>
        {/* You can add meta tags, link tags for fonts, etc. here */}
      </head>
      <body>
        {/* AuthContextProvider wraps the entire application content that needs authentication context */}
        <AuthContextProvider>
          {/* ResponsiveSidebar acts as the main layout component, containing both the sidebar and the main content area. */}
          {/* The 'children' prop (which represents the page content, e.g., incoming-documents/page.tsx)
              is passed into the ResponsiveSidebar component. */}
          {/* <ResponsiveSidebar> */}
            {children}
          {/* </ResponsiveSidebar> */}
        </AuthContextProvider>
      </body>
    </html>
  );
}
